variables:
  DOCKER_DRIVER: overlay2

image: myood/godot-ci-android-export:godot-3.3

stages:
  - export

before_script:
  # Config sanity check
  - bash -c -- "[[ $K8S_SECRET_RELEASE_KEYSTORE_BASE64 != '' ]]"
  - bash -c -- "[[ $K8S_SECRET_RELEASE_KEYSTORE_USER != '' ]]"
  - bash -c -- "[[ $K8S_SECRET_RELEASE_KEYSTORE_PASSWORD != '' ]]"
  - grep -F "export/android/debug_keystore =" ~/.config/godot/editor_settings-3.tres | grep '".*"' -o | xargs ls
  - grep -F "export/android/android_sdk_path =" ~/.config/godot/editor_settings-3.tres | grep '".*"' -o | xargs ls
  # Setup build
  - chmod +x android/build/gradlew
  - sed "s@\(minSdk[[:space:]]\+:[[:space:]]\+\)[[:digit:]]\+@\121@g" -i android/build/config.gradle
  # Setup release keystore
  - echo $K8S_SECRET_RELEASE_KEYSTORE_BASE64 | base64 --decode > /root/release.keystore
  - sed 's@keystore/release[[:space:]]*=[[:space:]]*".*"@keystore/release = "/root/release.keystore"@g' -i export_presets.cfg
  - sed 's@keystore/release_password[[:space:]]*=[[:space:]]*".*"@keystore/release_password="'$K8S_SECRET_RELEASE_KEYSTORE_PASSWORD'"@g' -i export_presets.cfg
  - sed 's@keystore/release_user[[:space:]]*=[[:space:]]*".*"@keystore/release_user="'$K8S_SECRET_RELEASE_KEYSTORE_USER'"@g' -i export_presets.cfg
  
android_debug:
  stage: export
  when: manual
  script:
    - godot --verbose --debug --export-debug "Android Debug" dungeon-puzzle-debug.apk
  artifacts: 
    name: android
    when: always
    paths:
      - dungeon-puzzle-debug.apk

android_release_armeabi:
  stage: export
  when: manual
  script:
    - godot --export "Android Release Armeabi" dungeon-puzzle-armeabi.apk
  artifacts: 
    name: release
    when: always
    paths:
      - dungeon-puzzle-armeabi.apk

android_release_arm:
  stage: export
  when: manual
  script:
    - godot --export "Android Release Arm" dungeon-puzzle-arm.apk
  artifacts: 
    name: release
    when: always
    paths:
      - dungeon-puzzle-arm.apk

android_release_x86:
  stage: export
  when: manual
  script:
    - godot --export "Android Release x86" dungeon-puzzle-x86.apk
  artifacts: 
    name: release
    when: always
    paths:
      - dungeon-puzzle-x86.apk

android_release_x86_64:
  stage: export
  when: manual
  script:
    - godot --export "Android Release x86_64" dungeon-puzzle-x86-64.apk
  artifacts: 
    name: release
    when: always
    paths:
      - dungeon-puzzle-x86-64.apk
